### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [jaketanda/Random-Image-Folder-to-Discord-Bot#1]
Does not pull any images in, regardless of the permissions given to the bot on the server - Have tested this by forcing the bot to send a known location of the image from the same directory as where it would be sourcing the images if it was "random" and it displays in the server without issue.

The random command also causes the bot to break/crash, unknown as to why.

**Comment by bodegahermosa** [comment]
Having the exact same issue. I followed the directions and necessary permissions accordingly and absolutely no images would be triggered by any commands.

**Comment by jaketanda** [comment]
Should have fixed your issues. Let me know if you're still having issues.

I have a version 2 bot that works much better (using urls rather than files) that I can upload if you guys are interested.

**Comment by bodegahermosa** [comment]
Thank you! Yeah, I'd be interested in seeing a URL variation.
