### ISSUE TITLE
So i 

### ISSUE THREAD

**Issue by Unknownio** [jaketanda/Random-Image-Folder-to-Discord-Bot#2]
I like to ask u do u like to join team 
team- well im searching for programmers that will join my team 
so far the team is not big but im inviting u to join

**Comment by Unknownio** [comment]
Look this is cool ,but how can i make it to give GIF

**Comment by jaketanda** [comment]
I have a new bot up that you can use to share gifs, videos, text, etc - Check it out [here](https://github.com/jaketanda/jankebot)
